[deploy]
bucket = 'cfn-artifacts-ferritinman'
region = 'ca-central-1'
stack_name = 'CrdSyncRole'

[parameters]
GitHubOrg = 'ferritinman'
RepositoryName = 'aws-bootcamp-cruddur-2023'
OIDCProviderArn = ''