[deploy]
bucket = 'cfn-artifacts-ferritinman'
region = 'ca-central-1'
stack_name = 'CrdServiceBackendFlask'

[parameters]
EnvFrontendUrl = 'https://ferritinman.com'
EnvBackendUrl = 'https://api.ferritinman.com'